services:
  database-posgres-practicas:
    image: postgres:17-trixie
    container_name: database-posgres-practicas
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - practicas_postgres_data:/var/lib/postgresql/data
      - ./tareas:/docker-entrypoint-initdb.d
    networks:
      - practicas_net

networks:
  practicas_net:
    name: practicas_net